dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - docker build -t travis-ci-build-stages-demo .
      - docker images
    - stage: test application
      script:
      - docker build -t travis-ci-build-stages-demo .
      - docker run travis-ci-build-stages-demo
    - stage: analyse code
      script:
      - echo "Analysing code:"
      - cat *.java
    - stage: push docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
      - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
